In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mariamburai030/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/mariamburai030/numpy-array-operations


'https://jovian.ai/mariamburai030/numpy-array-operations'

In [6]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.concatenate  # (change this)
function2 = np.sum
function3 = np.cross
function4 = np.arrange
function5 = np.sqrt

In [5]:
                          #Function 1 - np.concatenate (change this)
#Add some explanation about the function in your own words
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

In [8]:
# Example 2 - working
arr1 = [[2,3],[7,5]]

arr2 = [[1,6],[5,2]]

np.concatenate((arr1, arr2), axis=1)


array([[2, 3, 1, 6],
       [7, 5, 5, 2]])

In [9]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[2,3],
        [5,8]]


arr2 = [[5,6,7],
        [3,2,5]]
np.concatenate((arr1, arr2), axis=0)         # axis=0 , it should be the same column

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [10]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mariamburai030/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/mariamburai030/numpy-array-operations


'https://jovian.ai/mariamburai030/numpy-array-operations'

In [ ]:
                       #Function 2 -np.sum() 
#Add some explanations

In [18]:
# Example 1 - working
np.sum([0.5, 1.5])

2.0

In [20]:
# Example 2 - working
np.sum([[0, 1], [0, 5]], axis=0)      # sum from row
np.sum([[0, 1], [0, 5]], axis=1)      #sum from column 

array([1, 5])

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
np.sum([[0, 1], [0, 5]], axis=3)   # sum from the second column # there is no second column 

AxisError: axis 3 is out of bounds for array of dimension 2

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mariamburai030/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/mariamburai030/numpy-array-operations


'https://jovian.ai/mariamburai030/numpy-array-operations'

In [ ]:
                 #Function 3 -np.prod() 
#Add some explanations

In [24]:
# Example 1 - working
np.prod([[1.,2.],[3.,4.]], axis=0)   # product horizantal

array([3., 8.])

In [25]:
# Example 2 - working
np.prod([[1.,2.],[3.,4.]])   # ordinal product two dimesianl 

24.0

In [26]:
# Example 3 - breaking (to illustrate when it breaks)
np.prod([[1.,2.],[3.,4.]], axis=3)    # there is no second column

AxisError: axis 3 is out of bounds for array of dimension 2

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mariamburai030/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/mariamburai030/numpy-array-operations


'https://jovian.ai/mariamburai030/numpy-array-operations'

In [ ]:
                                    #Function 3 -np.cross
#Add some explanations

In [29]:
# Example 1 working
x = np.array([[1,2,3], [4,5,6]])

y = np.array([[4,5,6], [1,2,3]])

np.cross(x, y)

array([[-3,  6, -3],
       [ 3, -6,  3]])

In [30]:
# Example 2 working
np.cross(x, y, axisc=0)

array([[-3,  3],
       [ 6, -6],
       [-3,  3]])

In [31]:
# Example 3 not work
np.cross(x, y, axisc=4)

AxisError: axisc: axis 4 is out of bounds for array of dimension 2

In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mariamburai030/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/mariamburai030/numpy-array-operations


'https://jovian.ai/mariamburai030/numpy-array-operations'

In [34]:
                                    #Function 4 -np.arange
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr+10
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr/0
arr

<ipython-input-36-b3282f35305e>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0
<ipython-input-36-b3282f35305e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/0


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mariamburai030/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/mariamburai030/numpy-array-operations


'https://jovian.ai/mariamburai030/numpy-array-operations'

In [39]:
arr = [[-4,6],[7,8]]

np.sqrt(arr)



<ipython-input-39-2b6f58971e92>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[       nan, 2.44948974],
       [2.64575131, 2.82842712]])

In [40]:
jovian.commit()


<IPython.core.display.Javascript object>

[jovian] Updating notebook "mariamburai030/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/mariamburai030/numpy-array-operations


'https://jovian.ai/mariamburai030/numpy-array-operations'